### ISSUE TITLE
Does not toggle background

### ISSUE THREAD

**Issue by Kyoss79** [renatomoor/storybook-tailwind-dark-mode#9]
It apparently does not toggle the background of the storybook to dark, only applies the "dark" to the html.

It should also switch to dark background.

Keep up the good work :)

**Comment by tranttxuan** [comment]
I add .dark.body{ background: black }; in preview-head.html to switch to dark background-color.

**Comment by aaronleopold** [comment]
@Kyoss79 I create a `storybook.css` file that I import in the `preview.js` file that contains:

```css
html:not(.dark) > .sb-show-main {
	/* replace color */
	background: white !important;
}

.dark > .sb-show-main {
	/* replace color */
	background: dark !important;
}
```

However I agree, it would be nice if this was built in
